### ISSUE TITLE
Error in configuration.yaml

### ISSUE THREAD

**Issue by OGB1952** [dxoverdy/Integrating-Sofar2mqtt-with-Home-Assistant#1]
There's a duplicated mapping key at line 501 in the configuration.yaml file.  The section in tags below appears twice and throws an error:

`utility_meter_daily_sofar_battery_discharge:
    source: sensor.sofar_today_s_total_battery_discharge
    cycle: daily
    name: "SOFAR Utility Meter - Daily Total Battery Discharge"
    unique_id: "sofar_utility_meter_daily_total_battery_discharge"
    offset: 0
    delta_values: false
    net_consumption: false`

**Comment by dxoverdy** [comment]
I believe this has been resolved in the meantime as I have just checked and no two unique ids are alike.
