### ISSUE TITLE
coding instructions for battery save mode 

### ISSUE THREAD

**Issue by Romainiak** [dxoverdy/Integrating-Sofar2mqtt-with-Home-Assistant#4]
Dear Author 

My parents live in South Africa and face a lot of power outages roughly 2 per day. Is it possible to setup the raspberry pi to control the inverter to allow the battery to stay charged up when grid is connected discharge when grid fails and then when the grid comes back on recharge the battery and wait for the next grid failure. I do not want to use the self use mode of constantly charging and discharging. Also they are only now installing PV but currently the inverter is only running from the grid as a backup.

**Comment by dxoverdy** [comment]
Sorry, I can't assist I'm afraid.  It's beyond the remit of this project.  Perhaps try the author of Sofar2mqtt of the SOFAR Facebook group.

With thanks
